#########
host="localhost"
port=8080

######### Logging properties #########
### debug\error ###
log_level="debug"

######### Database properties #########
dbServer="mongodb://must:{AREMPLACER}@ds111885.mlab.com:11885/monogodb-db"
database="monogodb-db"
